[versions]
agp = "8.13.1"
androidTools = "31.13.1"
androidx-activity = "1.12.1"
androidx-lifecycle = "2.10.0"
androidx-test-espresso = "3.7.0"
androidx-test-ext = "1.3.0"
camerax_version = "1.5.1"
coil = "2.7.0"
koin = "4.1.1"
kotlin = "2.2.21"
kotlinxSerializationJsonVersion = "1.9.0"
ksp = "2.3.3"
nav-version = "2.9.6"
room-version = "2.8.4"
credentials = "1.5.0"
uiTestJunit4 = "1.10.0"
mockk = "1.14.7"
turbine = "1.2.1"
coroutines = "1.10.2"
junitKtx = "1.3.0"

[libraries]
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
android-tools-common = { module = "com.android.tools:common", version.ref = "androidTools" }
androidx-activity = { module = "androidx.activity:activity", version.ref = "androidx-activity" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-core-ktx = "androidx.test:core-ktx:1.7.0"
#Compose
androidx-ui = { module = "androidx.compose.ui:ui" }
androidx-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
# Gradle
build-gradle = { module = "com.android.tools.build:gradle", version.ref = "agp" }
coil = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
compose-bom = "androidx.compose:compose-bom:2025.12.00"
compose-material3 = "androidx.compose.material3:material3:1.4.0"
compose-material_icons_extends = "androidx.compose.material:material-icons-extended:1.7.8"
compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "nav-version" }
compose-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
compose-ui-test = { module = "androidx.compose.ui:ui-test-junit4" }
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
firebase-auth = { module = "com.google.firebase:firebase-auth" }
google-auth = "com.google.android.gms:play-services-auth:21.4.0"
google-identity = "com.google.android.libraries.identity.googleid:googleid:1.1.1"
androidx-credentials-core = { group = "androidx.credentials", name = "credentials", version.ref = "credentials" }
androidx-credentials-compat = { group = "androidx.credentials", name = "credentials-play-services-auth", version.ref = "credentials" }
firebase-bom = "com.google.firebase:firebase-bom:34.6.0"
crashlytics-gradle = "com.google.firebase:firebase-crashlytics-gradle:3.0.6"
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
firebase-database = { module = "com.google.firebase:firebase-database" }
firebase-firestore = { module = "com.google.firebase:firebase-firestore" }
firebase-storage = { module = "com.google.firebase:firebase-storage" }
google-services = "com.google.gms:google-services:4.4.4"
junit = "junit:junit:4.13.2"
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin"}
koin-junit4 = { module = "io.insert-koin:koin-test-junit4", version.ref = "koin"}
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockk" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJsonVersion" }
ksp-gradlePlugin = { module = "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
lifecycle-compose-runtime = { module = "androidx.lifecycle:lifecycle-runtime-compose" }
lifecycle-compose-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-compose" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room-version" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room-version" }
splashscreen = "androidx.core:core-splashscreen:1.2.0"
test-espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-test-espresso" }
test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-ext" }
timber = "com.jakewharton.timber:timber:5.0.1"
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "uiTestJunit4" }
androidx-junit-ktx = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "junitKtx" }

[bundles]
compose = [
    "activity-compose",
    "coil",
    "compose-material3",
    "compose-material_icons_extends",
    "compose-navigation",
    "compose-preview",
    "compose-ui",
    "compose-ui-graphics",
    "lifecycle-compose-runtime",
    "lifecycle-compose-viewmodel",
]
firebase = [
    "firebase-auth",
    "firebase-crashlytics",
    "firebase-database",
    "firebase-firestore",
    "firebase-storage",
]
koin = [
    "koin-android",
    "koin-core",
]
koin-compose = [
    "koin-android",
    "koin-androidx-compose",
    "koin-core",
]

unit-test = [
    "junit",
    "kotlinx-coroutines-test",
    "mockk",
    "koin-test",
    "koin-junit4"
]

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
jetbrains-kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kspPlugin = { id = "com.google.devtools.ksp", version.ref = "ksp" }
# Own Plugins
loperilla-application-compose = { id = "homeshopping.application.compose" }
loperilla-application = { id = "homeshopping.android.application" }
loperilla-feature-ui = { id = "homeshopping.feature.ui" }
loperilla-jvm-library = { id = "homeshopping.jvm.library" }
loperilla-library = { id = "homeshopping.android.library" }
loperilla-library-compose = { id = "homeshopping.library.compose" }
version-catalog-update = "nl.littlerobots.version-catalog-update:1.0.1"
